[package]
name = "rmatrix"
version = "0.1.0"
authors = ["Roee Nizan <roeen30@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26"
rand = "0.8"
ctrlc = "3.2"
