[package]
name = "rmatrix"
version = "0.1.0"
authors = ["Roee Nizan <roeen30@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
rand = "0.8.2"
ctrlc = "*"
